"""empty message

Revision ID: 352e00af75e8
Revises: 
Create Date: 2018-11-09 07:11:45.620408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '352e00af75e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_dttm', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('registry_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('established', sa.Date(), nullable=False),
    sa.Column('total_capital', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_established'), 'company', ['established'], unique=False)
    op.create_index(op.f('ix_company_name'), 'company', ['name'], unique=False)
    op.create_index(op.f('ix_company_registry_id'), 'company', ['registry_id'], unique=True)
    op.create_table('individual',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_dttm', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('identificator', sa.BIGINT(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identificator')
    )
    op.create_index(op.f('ix_individual_first_name'), 'individual', ['first_name'], unique=False)
    op.create_index(op.f('ix_individual_last_name'), 'individual', ['last_name'], unique=False)
    op.create_table('juridicial_persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_dttm', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('registry_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_juridicial_persons_name'), 'juridicial_persons', ['name'], unique=False)
    op.create_index(op.f('ix_juridicial_persons_registry_id'), 'juridicial_persons', ['registry_id'], unique=True)
    op.create_table('jp_owner_association',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('owned_id', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Float(), nullable=True),
    sa.Column('dttm', sa.DateTime(), nullable=True),
    sa.Column('founder', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['owned_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['juridicial_persons.id'], ),
    sa.PrimaryKeyConstraint('id', 'owner_id', 'owned_id')
    )
    op.create_table('np_owner_association',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('owned_id', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Float(), nullable=True),
    sa.Column('dttm', sa.DateTime(), nullable=True),
    sa.Column('founder', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['owned_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['individual.id'], ),
    sa.PrimaryKeyConstraint('id', 'owner_id', 'owned_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('np_owner_association')
    op.drop_table('jp_owner_association')
    op.drop_index(op.f('ix_juridicial_persons_registry_id'), table_name='juridicial_persons')
    op.drop_index(op.f('ix_juridicial_persons_name'), table_name='juridicial_persons')
    op.drop_table('juridicial_persons')
    op.drop_index(op.f('ix_individual_last_name'), table_name='individual')
    op.drop_index(op.f('ix_individual_first_name'), table_name='individual')
    op.drop_table('individual')
    op.drop_index(op.f('ix_company_registry_id'), table_name='company')
    op.drop_index(op.f('ix_company_name'), table_name='company')
    op.drop_index(op.f('ix_company_established'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
